application: plainsq-hrd
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /favicon.ico
  static_files: favicon.ico
  upload: favicon.ico
- url: /admin/.*
  script: google.appengine.ext.admin.application
  login: admin
- url: /(.*\.js)
  static_files: \1
  upload: .*\.js
- url: /(.*\.css)
  static_files: \1
  upload: .*\.css
- url: .*
  script: main.app

admin_console:
  pages:
  - name: My Console
    url: /admin/interactive
  - name: My Memcache
    url: /admin/memcache
  - name: My XMPP
    url: /admin/xmpp
  - name: My Inbound Mail
    url: /admin/inboundmail

libraries:
- name: PIL
  version: latest
- name: jinja2
  version: latest
- name: markupsafe
  version: latest

